Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.synced_folder "salt", "/srv/salt/"
  config.vm.synced_folder "pillar", "/srv/pillar" 
  config.vm.synced_folder "../", "/srv/formulas/ipython-notebook-formula" 


  config.vm.provision :salt do |salt|
    salt.minion_config = "salt/minion"
    salt.run_highstate = true
  #get the git development version of salt, the ppa falls out of date
    salt.install_type = 'git'
    salt.install_args = 'develop'
  end

  # some stuff to test the ipython notebook server
  config.vm.network "forwarded_port", guest: 8080, host: 8080
end
